#!/bin/sh
# ─────────────────────────────────────────────────────────────────────────────
#  Focus agent — the whole thing, in this one file. Linux and macOS.
# ─────────────────────────────────────────────────────────────────────────────
#
#   sh focus-agent-linux.sh                install everything and start it
#   sh focus-agent-linux.sh --autostart    …and start it at every login
#   sh focus-agent-linux.sh --no-bridge    skip the GNOME Shell bridge
#   sh focus-agent-linux.sh --no-start     install but do not launch it
#   sh focus-agent-linux.sh --uninstall    stop it and remove everything
#
# This file CARRIES the agent: its compiled JavaScript, its source, the launcher,
# the icon installer, the GNOME Shell bridge and the licence are all embedded at the
# bottom as base64. It downloads nothing and needs no network, no git, no npm and no
# TypeScript — only Node.js, which is what the agent itself runs on.
#
# That is deliberate. Every alternative shape was worse: an installer that clones the
# repository needs the repository to be public and to stay at a URL; one that fetches
# a release needs a release per change; and one that only unpacks source needs a
# toolchain on a machine where the user wanted to install one 350-line helper. One
# file, one command, and nothing that can 404 six months from now.
#
# GENERATED by scripts/build-agent-installer.mjs from desktop/install/template.sh —
# edit the template, not this file, and run `npm run build`.
#
# Nothing needs root. Everything is written under your home directory, and
# --uninstall removes exactly what was written.
set -eu

OS=$(uname -s)
case "$OS" in
  Linux)  DEST=${FOCUS_DIR:-"${XDG_DATA_HOME:-$HOME/.local/share}/focus-agent"} ;;
  Darwin) DEST=${FOCUS_DIR:-"$HOME/Library/Application Support/focus-agent"} ;;
  *)
    echo "This installer covers Linux and macOS." >&2
    echo "On Windows, download and run the .ps1 installer instead." >&2
    exit 1
    ;;
esac

AUTOSTART=0
BRIDGE=1
START=1
MODE=install
for arg in "$@"; do
  case "$arg" in
    --autostart|autostart) AUTOSTART=1 ;;
    --no-bridge)           BRIDGE=0 ;;
    --no-start)            START=0 ;;
    --uninstall|uninstall) MODE=uninstall ;;
    -h|--help)             sed -n '4,10p' "$0" | sed 's/^#[[:space:]]\{0,1\}//'; exit 0 ;;
    *) echo "Unknown option: $arg (try --help)" >&2; exit 1 ;;
  esac
done

say()  { printf '\n\033[1m▸ %s\033[0m\n' "$1"; }
note() { printf '  %s\n' "$1"; }
die()  { printf '\n\033[31m✗ %s\033[0m\n' "$1" >&2; exit 1; }

# ── Uninstall ────────────────────────────────────────────────────────────────
# First, so removing a half-broken install never depends on anything below it.
if [ "$MODE" = uninstall ]; then
  say "Removing the Focus agent"
  [ -f "$DEST/launch.sh" ] && sh "$DEST/launch.sh" stop >/dev/null 2>&1 || true
  [ -f "$DEST/install-icon.sh" ] && sh "$DEST/install-icon.sh" --uninstall >/dev/null 2>&1 || true
  rm -rf "$DEST"
  note "Deleted $DEST and the desktop icon."
  note "The GNOME bridge is separate. If you installed one:"
  note "  gnome-extensions disable focus-companion@focus.dev"
  note "  rm -rf ~/.local/share/gnome-shell/extensions/focus-companion@focus.dev"
  note "Your scores, whitelists and settings live in the extension and are untouched."
  exit 0
fi

# ── Node ─────────────────────────────────────────────────────────────────────
# Found rather than assumed, for the reason launch.sh spells out at length: a node
# installed by nvm or Homebrew is on your shell's PATH and nowhere else. Not
# installed for you — a language runtime is a decision about the machine, not a side
# effect of installing a helper. It is also what unpacks this file, below.
find_node() {
  if command -v node >/dev/null 2>&1; then command -v node; return 0; fi
  for c in /usr/local/bin/node /usr/bin/node /opt/homebrew/bin/node /snap/bin/node; do
    [ -x "$c" ] && { echo "$c"; return 0; }
  done
  for c in $(ls -d "$HOME"/.nvm/versions/node/*/bin/node 2>/dev/null | sort -Vr); do
    [ -x "$c" ] && { echo "$c"; return 0; }
  done
  return 1
}

say "Looking for Node.js"
NODE=$(find_node) || {
  case "$OS" in
    Darwin) die "Node.js not found. Install it with 'brew install node' or from https://nodejs.org, then run this again." ;;
    *)      die "Node.js not found. Install it with your package manager (apt install nodejs · dnf install nodejs · pacman -S nodejs), or from https://nodejs.org, then run this again." ;;
  esac
}
note "node $("$NODE" --version) — the agent runs on this, and it unpacks this file"

# ── Unpacking ────────────────────────────────────────────────────────────────
# Decoded by node itself rather than by `base64` and `tar`: BSD and GNU base64
# disagree about the decode flag (-D vs -d), tar disagrees about wildcards, and node
# is already a hard requirement three lines above. One decoder, no dependencies, and
# gzip so the file stays small enough to be a download rather than a distribution.
DECODE='const z=require("zlib"),f=require("fs");let s="";process.stdin.setEncoding("ascii");process.stdin.on("data",c=>s+=c).on("end",()=>{f.mkdirSync(require("path").dirname(process.argv[1]),{recursive:true});f.writeFileSync(process.argv[1],z.gunzipSync(Buffer.from(s,"base64")))})'

unpack() {
  printf '%s' "$2" | "$NODE" -e "$DECODE" "$DEST/$1" \
    || die "Could not write $DEST/$1"
}

say "Unpacking the agent"
mkdir -p "$DEST"
#__PAYLOAD__
chmod +x "$DEST/launch.sh" "$DEST/install-icon.sh" 2>/dev/null || true
[ -f "$DEST/gnome-extension/install.sh" ] && chmod +x "$DEST/gnome-extension/install.sh" 2>/dev/null || true
note "$DEST"
note "Already built — dist/index.js is inside this file, so there is nothing to compile."

# ── Clickable icon ───────────────────────────────────────────────────────────
say "Installing the icon"
if [ "$AUTOSTART" = 1 ]; then
  sh "$DEST/install-icon.sh" --autostart
else
  sh "$DEST/install-icon.sh"
fi

# ── GNOME bridge (Linux only) ────────────────────────────────────────────────
# On Wayland this is not a nicety: a Wayland client may not see other applications'
# windows at all, so without code running inside the compositor the agent has nothing
# to report. It is also the only thing that can pin and fade the companion window
# there. Installed by default on a GNOME session, because anyone able to answer
# "should I install the bridge?" would have had to know all of that first.
BRIDGE_DONE=0
is_gnome() {
  case "${XDG_CURRENT_DESKTOP:-}:${DESKTOP_SESSION:-}:${GNOME_SHELL_SESSION_MODE:-}" in
    *GNOME*|*gnome*) return 0 ;;
  esac
  return 1
}
if [ "$OS" = Linux ] && [ "$BRIDGE" = 1 ] && is_gnome && [ -f "$DEST/gnome-extension/install.sh" ]; then
  say "Installing the GNOME Shell bridge"
  if sh "$DEST/gnome-extension/install.sh"; then BRIDGE_DONE=1; fi
fi

# ── Start ────────────────────────────────────────────────────────────────────
if [ "$START" = 1 ]; then
  say "Starting it"
  sh "$DEST/launch.sh" || true
  sh "$DEST/launch.sh" status || note "Not answering yet — click the Focus agent icon to try again."
fi

# ── What just happened, and what this platform cannot do ─────────────────────
say "Done"
note "Installed in: $DEST"
note "Start / stop: the \"Focus agent\" icon, or  sh '$DEST/launch.sh' [stop|status]"
note "Uninstall:    sh $(basename "$0") --uninstall   (this same file)"
echo
note "Now open the extension popup and whitelist the program you are working in:"
note "the companion's second bar offers whatever is in front of you with one click."

if [ "$OS" = Darwin ]; then
  cat <<'EOF'

  ⚠ Two things are not available on macOS, and no version of this agent can add them:

    • The floating companion window cannot be kept ON TOP automatically. No public
      API lets one process change another application's window level, which is why
      every tool that does it is an Accessibility-granted window manager. Use
      Rectangle (enable "Always on Top") or Amethyst, and grant it Accessibility.
    • That window cannot be made SEE-THROUGH either. Same reason one layer down: the
      translucency is applied from outside the window — by the compositor on GNOME,
      by this agent on Windows. macOS allows neither.

  Everything the agent senses works normally: the foreground application is read
  with `lsappinfo`, which needs no Accessibility or Automation permission, and no
  window title is ever read.
EOF
fi

if [ "$BRIDGE_DONE" = 1 ]; then
  cat <<'EOF'

  ⚠ LOG OUT AND BACK IN to finish the GNOME bridge. There is no way around it:
    GNOME Shell scans for new extensions only at start-up, and it cannot be
    restarted in place on Wayland. Until then a Wayland session reports no program
    (an X11 session works immediately) and the companion window will not pin itself.
EOF
elif [ "$OS" = Linux ] && [ "$BRIDGE" = 1 ] && ! is_gnome; then
  cat <<'EOF'

  ⚠ This is not a GNOME session, so nothing was installed inside the compositor.
    On X11 that is fine — the agent reads the foreground window with xprop and needs
    nothing else. On a non-GNOME WAYLAND session (KDE, sway, Hyprland) no program can
    be reported at all: a Wayland client may not see other applications' windows, and
    only code inside the compositor can. Page tracking in the browser is unaffected;
    the program whitelist simply never matches.
EOF
fi
echo
