# ─────────────────────────────────────────────────────────────────────────────
#  Focus agent — the whole thing, in this one file. Windows.
# ─────────────────────────────────────────────────────────────────────────────
#
#   powershell -ExecutionPolicy Bypass -File focus-agent-windows.ps1
#   powershell -ExecutionPolicy Bypass -File focus-agent-windows.ps1 -Autostart
#   powershell -ExecutionPolicy Bypass -File focus-agent-windows.ps1 -NoStart
#   powershell -ExecutionPolicy Bypass -File focus-agent-windows.ps1 -Uninstall
#
# The Windows half of the POSIX installer, and the same bargain: this file CARRIES the
# agent — compiled JavaScript, source, launcher, shortcut installer and licence, all
# embedded at the bottom as base64. It downloads nothing and needs no network, no git,
# no npm and no TypeScript; only Node.js, which is what the agent runs on.
#
# -ExecutionPolicy Bypass appears in every line above because Windows blocks a script
# downloaded from the internet by default, and "just double-click it" would be a lie.
#
# GENERATED by scripts/build-agent-installer.mjs from desktop/install/template.ps1 —
# edit the template, not this file, and run `npm run build`.
#
# Nothing needs administrator rights. Everything is written under your own profile,
# and -Uninstall removes exactly what was written.
param(
  [switch]$Autostart,
  [switch]$NoStart,
  [switch]$Uninstall
)

$ErrorActionPreference = 'Stop'
$dest = if ($env:FOCUS_DIR) { $env:FOCUS_DIR } else { Join-Path $env:LOCALAPPDATA 'focus-agent' }

function Say  ($m) { Write-Host ''; Write-Host "> $m" -ForegroundColor White }
function Note ($m) { Write-Host "  $m" -ForegroundColor DarkGray }
function Die  ($m) { Write-Host ''; Write-Host "x $m" -ForegroundColor Red; exit 1 }

# ── Uninstall ────────────────────────────────────────────────────────────────
# First, so removing a half-broken install never depends on anything below it.
if ($Uninstall) {
  Say 'Removing the Focus agent'
  # `$agentPid`, not `$pid`: that one is a read-only automatic variable holding this
  # shell's own process id, and assigning to it would fail the script on the first
  # line of the path that has to work when everything else is broken.
  try {
    $agentPid = (Invoke-RestMethod -Uri 'http://127.0.0.1:47317/' -TimeoutSec 2).pid
    if ($agentPid) {
      Stop-Process -Id $agentPid -Force -ErrorAction SilentlyContinue
      Note "Stopped the agent (pid $agentPid)."
    }
  } catch { Note 'The agent was not running.' }

  $icon = Join-Path $dest 'install-icon.ps1'
  if (Test-Path $icon) {
    & powershell -NoProfile -ExecutionPolicy Bypass -File $icon -Uninstall | Out-Null
  }
  Remove-Item (Join-Path ([Environment]::GetFolderPath('Startup')) 'Focus agent.lnk') -ErrorAction SilentlyContinue
  if (Test-Path $dest) { Remove-Item $dest -Recurse -Force }
  Note "Deleted $dest and the shortcuts."
  Note 'Your scores, whitelists and settings live in the extension and are untouched.'
  return
}

# ── Node ─────────────────────────────────────────────────────────────────────
# Not installed for you: a language runtime is a decision about the machine, not a
# side effect of installing a helper.
Say 'Looking for Node.js'
if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
  Die 'Node.js not found. Install it from https://nodejs.org (or run "winget install OpenJS.NodeJS.LTS"), reopen PowerShell, then run this again.'
}
Note "node $(node --version) - the agent runs on this"

# ── Unpacking ────────────────────────────────────────────────────────────────
# .NET does the decoding, so this needs nothing installed — no tar.exe (absent before
# Windows 10 1803), no Expand-Archive quirks, and no second file to fetch.
function Unpack ($rel, $b64) {
  $path = Join-Path $dest $rel
  New-Item -ItemType Directory -Force -Path (Split-Path -Parent $path) | Out-Null
  # `(, $bytes)` is the unary-comma trick: without it PowerShell splats the byte array
  # into the constructor's parameters and no MemoryStream overload matches. Kept on its
  # own line with a variable rather than an inline call, where the same trick is fragile.
  $bytes = [Convert]::FromBase64String($b64)
  $gz  = New-Object IO.MemoryStream(, $bytes)
  $out = New-Object IO.MemoryStream
  $s   = New-Object IO.Compression.GZipStream($gz, [IO.Compression.CompressionMode]::Decompress)
  try { $s.CopyTo($out) } finally { $s.Dispose(); $gz.Dispose() }
  [IO.File]::WriteAllBytes($path, $out.ToArray())
  $out.Dispose()
}

Say 'Unpacking the agent'
New-Item -ItemType Directory -Force -Path $dest | Out-Null
#__PAYLOAD__
Note $dest
Note 'Already built - dist\index.js is inside this file, so there is nothing to compile.'

# ── Shortcuts ────────────────────────────────────────────────────────────────
Say 'Installing the shortcut'
& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $dest 'install-icon.ps1')

if ($Autostart) {
  # The same shortcut again, in the folder Windows runs at login. Opt-in, because
  # clicking an icon is one decision and starting with the session is another.
  $startup = Join-Path ([Environment]::GetFolderPath('Startup')) 'Focus agent.lnk'
  $onDesk  = Join-Path ([Environment]::GetFolderPath('Desktop')) 'Focus agent.lnk'
  if (Test-Path $onDesk) { Copy-Item $onDesk $startup -Force; Note "Starts at login: $startup" }
}

# ── Start ────────────────────────────────────────────────────────────────────
if (-not $NoStart) {
  Say 'Starting it'
  # Through the generated launch.vbs, which is what the shortcut runs: window style 0,
  # so no console flashes. node.exe from a shortcut always shows one.
  $vbs = Join-Path $dest 'launch.vbs'
  if (Test-Path $vbs) { Start-Process -FilePath 'wscript.exe' -ArgumentList "`"$vbs`"" }
  else { Start-Process -WindowStyle Hidden -FilePath 'node' -ArgumentList "`"$(Join-Path $dest 'dist\index.js')`"" }
  Start-Sleep -Seconds 2
  try {
    $r = Invoke-RestMethod -Uri 'http://127.0.0.1:47317/' -TimeoutSec 2
    Note "Running (pid $($r.pid)). Programs on your list now count as work."
  } catch {
    Note 'Not answering yet - double-click the "Focus agent" shortcut to try again.'
  }
}

# ── What just happened ───────────────────────────────────────────────────────
Say 'Done'
Note "Installed in: $dest"
Note 'Start:     the "Focus agent" shortcut on your Desktop or in the Start menu'
Note 'Stop:      end the node.exe task in Task Manager'
Note "Uninstall: powershell -ExecutionPolicy Bypass -File `"$($MyInvocation.MyCommand.Path)`" -Uninstall"
Write-Host ''
Note 'Windows gets every feature: the foreground program, and this agent also pins the'
Note 'floating companion window on top and fades it (FOCUS_COMPANION_OPACITY, 100-255).'
Note 'Now open the extension popup and whitelist the program you are working in - the'
Note 'companion offers whatever is in front of you with one click.'
Write-Host ''
