# Put a "Focus agent" shortcut on the Desktop and in the Start menu. Clicking it
# starts the agent.
#
#   powershell -ExecutionPolicy Bypass -File install-icon.ps1
#   powershell -ExecutionPolicy Bypass -File install-icon.ps1 -Uninstall
#
# Nothing needs administrator rights; everything is written under your own profile.
param([switch]$Uninstall)

$ErrorActionPreference = 'Stop'
$dir     = Split-Path -Parent $MyInvocation.MyCommand.Path
$agent   = Join-Path $dir 'dist\index.js'
$vbs     = Join-Path $dir 'launch.vbs'
$desktop = [Environment]::GetFolderPath('Desktop')
$start   = Join-Path ([Environment]::GetFolderPath('StartMenu')) 'Programs'
$links   = @((Join-Path $desktop 'Focus agent.lnk'), (Join-Path $start 'Focus agent.lnk'))

if ($Uninstall) {
  $links | Where-Object { Test-Path $_ } | Remove-Item
  if (Test-Path $vbs) { Remove-Item $vbs }
  Write-Host 'Removed the Focus agent shortcuts. Stop a running agent from Task Manager (node.exe).'
  return
}

if (-not (Test-Path $agent)) {
  Write-Host 'Building the agent first...'
  Push-Location $dir; npm install; npm run build; Pop-Location
}

# WScript is what makes the click silent. Running node.exe from a shortcut always
# flashes a console window, however the shortcut is configured — a .vbs host with
# window style 0 is the only way to start it without one.
@"
' Starts the Focus agent with no console window. Generated by install-icon.ps1.
Set sh = CreateObject("WScript.Shell")
sh.Run "node ""$($agent -replace '"','""')""", 0, False
"@ | Set-Content -Path $vbs -Encoding ASCII

$shell = New-Object -ComObject WScript.Shell
foreach ($link in $links) {
  New-Item -ItemType Directory -Force -Path (Split-Path $link) | Out-Null
  $s = $shell.CreateShortcut($link)
  $s.TargetPath       = "$env:SystemRoot\System32\wscript.exe"
  $s.Arguments        = """$vbs"""
  $s.WorkingDirectory = $dir
  $s.Description      = 'Let the Focus extension see which program you are working in'
  $s.IconLocation     = "$env:SystemRoot\System32\shell32.dll,13"
  $s.Save()
}

Write-Host "Installed:"
$links | ForEach-Object { Write-Host "  $_" }
Write-Host ''
Write-Host 'Double-click it to start the agent. Nothing appears — that is expected;'
Write-Host 'the extension popup shows a green "agent on" dot once it is up.'
Write-Host 'To start it with Windows, copy the shortcut into: shell:startup'
Write-Host 'To stop it: end the node.exe task in Task Manager.'
