#!/bin/sh
# What the desktop icon runs.
#
# The agent has no window, so a double-click would otherwise look like nothing
# happened. This wrapper gives it the two things a clickable program needs: it says
# whether it worked, and it refuses to start a second copy. Everything else is the
# same `node dist/index.js` you would run by hand.
#
#   ./launch.sh          start it (or report that it is already running)
#   ./launch.sh stop     stop it
#   ./launch.sh status   say whether it is answering
#
# Kept as a plain POSIX script rather than generated by the installer so that what
# the icon does stays readable, and so moving the folder only means re-running the
# installer rather than hunting for a path baked into a file somewhere else.
set -u

PORT=47317                    # must match src/index.ts and the extension's manifest
DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
AGENT="$DIR/dist/index.js"

if [ "$(uname -s)" = "Darwin" ]; then
  LOG="$HOME/Library/Logs/focus-agent.log"
else
  LOG="${XDG_STATE_HOME:-$HOME/.local/state}/focus-agent.log"
fi

# ── Feedback ─────────────────────────────────────────────────────────────────
# Best effort by design: a missing notifier must never stop the agent starting.
notify() {
  if command -v notify-send >/dev/null 2>&1; then
    notify-send -a "Focus agent" "$1" "$2" 2>/dev/null
  elif command -v osascript >/dev/null 2>&1; then
    osascript -e "display notification \"$2\" with title \"$1\"" 2>/dev/null
  fi
  echo "$1: $2"
}

# ── Node ─────────────────────────────────────────────────────────────────────
# A desktop launcher does NOT inherit the PATH from your shell's rc file, so a node
# installed by nvm or Homebrew is invisible to it even though `node` works fine in a
# terminal. Hence the search: PATH first, then the usual install locations, then the
# newest nvm version.
find_node() {
  if command -v node >/dev/null 2>&1; then command -v node; return 0; fi
  for c in /usr/local/bin/node /usr/bin/node /opt/homebrew/bin/node /snap/bin/node; do
    [ -x "$c" ] && { echo "$c"; return 0; }
  done
  for c in $(ls -d "$HOME"/.nvm/versions/node/*/bin/node 2>/dev/null | sort -Vr); do
    [ -x "$c" ] && { echo "$c"; return 0; }
  done
  return 1
}

NODE=$(find_node) || {
  notify "Focus agent" "Node.js not found — install it, then click again."
  exit 1
}

# Is something already answering on the port? Asked with node itself, so this works
# on a machine with no curl. Any answer at all means an agent is up; two copies
# cannot both hold the port anyway, so this only makes the failure legible.
running() {
  "$NODE" -e "
    require('http').get('http://127.0.0.1:$PORT/', () => process.exit(0))
      .on('error', () => process.exit(1)).setTimeout(1200, () => process.exit(1));
  " 2>/dev/null
}

# The pid of whatever is answering on the port, from the agent's own reply.
agent_pid() {
  "$NODE" -e "
    require('http').get('http://127.0.0.1:$PORT/', (r) => {
      let b = ''; r.on('data', (c) => b += c);
      r.on('end', () => {
        try { const p = JSON.parse(b).pid; if (p) { console.log(p); process.exit(0); } } catch {}
        process.exit(1);
      });
    }).on('error', () => process.exit(1)).setTimeout(1200, () => process.exit(1));
  " 2>/dev/null
}

case "${1:-start}" in
  status)
    if running; then echo "Focus agent: running on 127.0.0.1:$PORT"; exit 0; fi
    echo "Focus agent: not running"; exit 1
    ;;
  stop)
    if ! running; then notify "Focus agent" "Not running."; exit 0; fi
    # Ask the agent which process it is, rather than guessing from a command line:
    # `npm start`, this script and a hand-typed node invocation all look different,
    # and a pattern loose enough to catch all three would eventually catch something
    # else. pkill is only the fallback for an older agent that reports no pid.
    PID=$(agent_pid) || PID=''
    if [ -n "$PID" ]; then kill "$PID" 2>/dev/null; else pkill -f "$AGENT" 2>/dev/null; fi
    sleep 1
    if running; then notify "Focus agent" "Could not stop it — try: pkill -f dist/index.js"; exit 1; fi
    notify "Focus agent" "Stopped. Programs outside the browser no longer count."
    exit 0
    ;;
esac

if running; then
  notify "Focus agent" "Already running."
  exit 0
fi

# First click after a fresh clone: build it rather than failing with a path nobody
# can act on. Only ever needed once.
if [ ! -f "$AGENT" ]; then
  if command -v npm >/dev/null 2>&1; then
    npm --prefix "$DIR" run build >>"$LOG" 2>&1 || {
      notify "Focus agent" "Build failed — see $LOG"
      exit 1
    }
  else
    notify "Focus agent" "Not built yet. Run: cd $DIR && npm install && npm run build"
    exit 1
  fi
fi

mkdir -p "$(dirname "$LOG")"
# nohup + & so the agent outlives the click. The launcher exits immediately; the
# agent keeps the port until you stop it or log out.
nohup "$NODE" "$AGENT" >>"$LOG" 2>&1 &

# Long enough for a port bind to fail, short enough not to feel like a hang.
sleep 1
if running; then
  notify "Focus agent" "Running. Programs on your list now count as work."
  exit 0
fi
notify "Focus agent" "Failed to start — see $LOG"
exit 1
