#!/bin/sh
# What the desktop icon runs.
#
# The agent has no window, so a double-click would otherwise look like nothing
# happened. This wrapper gives it the two things a clickable program needs: it says
# whether it worked, and it refuses to start a second copy. Everything else is the
# same `node dist/index.js` you would run by hand.
#
#   ./launch.sh          start it (or report that it is already running)
#   ./launch.sh stop     stop it
#   ./launch.sh status   say whether it is answering
#   ./launch.sh remove   uninstall the whole desktop half, after asking
#
# Kept as a plain POSIX script rather than generated by the installer so that what
# the icon does stays readable, and so moving the folder only means re-running the
# installer rather than hunting for a path baked into a file somewhere else.
set -u

PORT=47317                    # must match src/index.ts and the extension's manifest
DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
AGENT="$DIR/dist/index.js"

# Where the one-file installer puts things — the same two paths template.sh computes,
# `FOCUS_DIR` included. `remove` deletes $DIR only when the two match, which is what
# stops it erasing a git working tree; see the case below.
if [ "$(uname -s)" = "Darwin" ]; then
  INSTALL_DEST=${FOCUS_DIR:-"$HOME/Library/Application Support/focus-agent"}
else
  INSTALL_DEST=${FOCUS_DIR:-"${XDG_DATA_HOME:-$HOME/.local/share}/focus-agent"}
fi

GNOME_UUID=focus-companion@focus.dev

if [ "$(uname -s)" = "Darwin" ]; then
  LOG="$HOME/Library/Logs/focus-agent.log"
else
  LOG="${XDG_STATE_HOME:-$HOME/.local/state}/focus-agent.log"
fi

# ── Feedback ─────────────────────────────────────────────────────────────────
# Best effort by design: a missing notifier must never stop the agent starting.
notify() {
  if command -v notify-send >/dev/null 2>&1; then
    notify-send -a "Focus agent" "$1" "$2" 2>/dev/null
  elif command -v osascript >/dev/null 2>&1; then
    osascript -e "display notification \"$2\" with title \"$1\"" 2>/dev/null
  fi
  echo "$1: $2"
}

# ── Asking before destroying ─────────────────────────────────────────────────
# `remove` is one line below "Stop the agent" in the same right-click menu, and a
# .desktop action runs the moment it is clicked — there is no dialog between the
# pointer and the deletion unless this puts one there. So unlike notify(), a missing
# dialog tool is NOT best-effort: with nothing able to ask, this refuses and prints
# the command instead. Removing somebody's install because their desktop happens to
# ship neither zenity nor kdialog is not a thing to fail open on.
#
# Returns 0 only on an explicit yes.
confirm() {
  if command -v zenity >/dev/null 2>&1; then
    zenity --question --title="Focus agent" --no-wrap \
           --ok-label="Remove" --cancel-label="Keep it" --text="$1" 2>/dev/null
  elif command -v kdialog >/dev/null 2>&1; then
    kdialog --title "Focus agent" --warningyesno "$1" 2>/dev/null
  elif command -v osascript >/dev/null 2>&1; then
    osascript -e "button returned of (display dialog \"$1\" with title \"Focus agent\" buttons {\"Keep it\", \"Remove\"} default button \"Keep it\")" 2>/dev/null \
      | grep -q Remove
  elif [ -t 0 ]; then
    # Run from a terminal: that is a dialog too, and the better one.
    printf '%s\n\nRemove it? [y/N] ' "$1"
    read -r answer
    case "$answer" in y|Y|yes|YES) return 0 ;; *) return 1 ;; esac
  else
    notify "Focus agent" "Cannot ask for confirmation here. To remove it, run: $DIR/launch.sh remove   from a terminal."
    return 1
  fi
}

# ── Node ─────────────────────────────────────────────────────────────────────
# A desktop launcher does NOT inherit the PATH from your shell's rc file, so a node
# installed by nvm or Homebrew is invisible to it even though `node` works fine in a
# terminal. Hence the search: PATH first, then the usual install locations, then the
# newest nvm version.
find_node() {
  if command -v node >/dev/null 2>&1; then command -v node; return 0; fi
  for c in /usr/local/bin/node /usr/bin/node /opt/homebrew/bin/node /snap/bin/node; do
    [ -x "$c" ] && { echo "$c"; return 0; }
  done
  for c in $(ls -d "$HOME"/.nvm/versions/node/*/bin/node 2>/dev/null | sort -Vr); do
    [ -x "$c" ] && { echo "$c"; return 0; }
  done
  return 1
}

NODE=$(find_node) || {
  notify "Focus agent" "Node.js not found — install it, then click again."
  exit 1
}

# Is something already answering on the port? Asked with node itself, so this works
# on a machine with no curl. Any answer at all means an agent is up; two copies
# cannot both hold the port anyway, so this only makes the failure legible.
running() {
  "$NODE" -e "
    require('http').get('http://127.0.0.1:$PORT/', () => process.exit(0))
      .on('error', () => process.exit(1)).setTimeout(1200, () => process.exit(1));
  " 2>/dev/null
}

# The pid of whatever is answering on the port, from the agent's own reply.
agent_pid() {
  "$NODE" -e "
    require('http').get('http://127.0.0.1:$PORT/', (r) => {
      let b = ''; r.on('data', (c) => b += c);
      r.on('end', () => {
        try { const p = JSON.parse(b).pid; if (p) { console.log(p); process.exit(0); } } catch {}
        process.exit(1);
      });
    }).on('error', () => process.exit(1)).setTimeout(1200, () => process.exit(1));
  " 2>/dev/null
}

case "${1:-start}" in
  status)
    if running; then echo "Focus agent: running on 127.0.0.1:$PORT"; exit 0; fi
    echo "Focus agent: not running"; exit 1
    ;;
  # ── Uninstall the whole desktop half ───────────────────────────────────────
  # Reachable from the icon's own right-click menu, because somebody who wants this
  # gone should not have to find a flag in a README — and for a study, being able to
  # withdraw without reading anything is a property of consent, not of convenience.
  #
  # It removes the three things the desktop side installed and nothing else: the
  # agent, the GNOME bridge, and the icons. The BROWSER EXTENSION is not touched and
  # cannot be from here — that is chrome://extensions, and the dialog says so rather
  # than leaving someone believing they have removed all of it.
  remove|uninstall)
    confirm "Remove the Focus desktop agent from this computer?

This stops the agent, removes the GNOME companion bridge and deletes the icons.
Your scores and settings are untouched — they belong to the browser extension,
which you remove separately from chrome://extensions." || { echo "Cancelled."; exit 0; }

    # 1. Stop it first: deleting the files under a running agent leaves a process with
    #    no script behind it and a port still held.
    if running; then
      PID=$(agent_pid) || PID=''
      if [ -n "$PID" ]; then kill "$PID" 2>/dev/null; else pkill -f "$AGENT" 2>/dev/null; fi
      sleep 1
    fi

    # 2. The GNOME bridge. Disabled BEFORE its directory goes, so the Shell — which
    #    still holds the loaded code — runs disable() and hands every companion window
    #    back at full opacity and un-pinned. Delete first and it cannot.
    if [ -d "$HOME/.local/share/gnome-shell/extensions/$GNOME_UUID" ]; then
      command -v gnome-extensions >/dev/null 2>&1 &&
        gnome-extensions disable "$GNOME_UUID" 2>/dev/null || true
      rm -rf "$HOME/.local/share/gnome-shell/extensions/$GNOME_UUID"
    fi

    # 3. The icons, including the autostart copy if there is one.
    [ -f "$DIR/install-icon.sh" ] && sh "$DIR/install-icon.sh" --uninstall >/dev/null 2>&1 || true

    # 4. The folder itself — ONLY when this is the copy the installer made.
    #
    #    This script also ships inside the repository, where $DIR is `desktop/` in a
    #    git working tree; `rm -rf` there would delete tracked source over a menu click
    #    somebody made to get rid of an icon. Comparing against the installer's own
    #    destination is the whole guard, and the else branch is the honest answer
    #    rather than a silent no-op.
    if [ "$DIR" = "$INSTALL_DEST" ]; then
      notify "Focus agent" "Removed."
      # exec, because `sh` reads a script as it runs: deleting the file out from under
      # the interpreter mid-execution is undefined. Replacing the process means nothing
      # further is read from it.
      exec rm -rf "$DIR"
    fi
    notify "Focus agent" "Stopped and unhooked. The folder is left alone: $DIR is not an installed copy."
    exit 0
    ;;

  stop)
    if ! running; then notify "Focus agent" "Not running."; exit 0; fi
    # Ask the agent which process it is, rather than guessing from a command line:
    # `npm start`, this script and a hand-typed node invocation all look different,
    # and a pattern loose enough to catch all three would eventually catch something
    # else. pkill is only the fallback for an older agent that reports no pid.
    PID=$(agent_pid) || PID=''
    if [ -n "$PID" ]; then kill "$PID" 2>/dev/null; else pkill -f "$AGENT" 2>/dev/null; fi
    sleep 1
    if running; then notify "Focus agent" "Could not stop it — try: pkill -f dist/index.js"; exit 1; fi
    notify "Focus agent" "Stopped. Programs outside the browser no longer count."
    exit 0
    ;;
esac

if running; then
  notify "Focus agent" "Already running."
  exit 0
fi

# First click after a fresh clone: build it rather than failing with a path nobody
# can act on. Only ever needed once.
if [ ! -f "$AGENT" ]; then
  if command -v npm >/dev/null 2>&1; then
    npm --prefix "$DIR" run build >>"$LOG" 2>&1 || {
      notify "Focus agent" "Build failed — see $LOG"
      exit 1
    }
  else
    notify "Focus agent" "Not built yet. Run: cd $DIR && npm install && npm run build"
    exit 1
  fi
fi

mkdir -p "$(dirname "$LOG")"
# nohup + & so the agent outlives the click. The launcher exits immediately; the
# agent keeps the port until you stop it or log out.
nohup "$NODE" "$AGENT" >>"$LOG" 2>&1 &

# Long enough for a port bind to fail, short enough not to feel like a hang.
sleep 1
if running; then
  notify "Focus agent" "Running. Programs on your list now count as work."
  exit 0
fi
notify "Focus agent" "Failed to start — see $LOG"
exit 1
